### ISSUE TITLE
Microverse Peer to Peer code review 04/29/2022 PR17

### ISSUE THREAD

**Issue by khitermedachraf** [HSMathebula/HSMathebula.github.io#21]
**Hello @HSMathebula 👋 you did Amazing work 🥇 .**
Clean Code 👍 .
Github workflow 👍 .
Here are some best practices maybe you can implement to improve your code:

- it is best practice to begin committing messages with caps so kindly consider that in subsequent commits
- Also it is a best practice to use the kebab-case method when creat your name classes. and keep going, Bro.

**Comment by GOlivierNation** [comment]
Good job @HSMathebula
